- name: Copy config file
  copy:
    src: /src/code/docker/website_ctl.conf
    dest: /etc/systemd/system/{{ DOMAIN }}.service
    remote_src: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable web service
  systemd:
    name: "{{ DOMAIN }}.service"
    state: restarted
    enabled: yes
