---
- name: Cài logrotate 
  apt:
    update_cache: yes
    state: present
    name: [
    'logrotate',
    ]

- name: Tạo config logrotate cho web service
  template:
    src: logrotate.d.j2
    dest: "/etc/logrotate.d/{{ DOMAIN }}"
  with_items:
    - path: "/src/code/logs/*.log"
      options:
        - su root root
        - daily
        - missingok
        - dateext
        - rotate 7
        - nocompress

- name: Tạo config logrotate cho nginx
  template:
    src: logrotate.d.j2
    dest: "/etc/logrotate.d/nginx"
  with_items:
    - path: "/etc/logrotate.d/nginx"
      options:
        - daily
        - missingok
        - rotate 14
        - compress
        - delaycompress
        - notifempty
        - create 0640 www-data adm
        - sharedscripts
        - prerotate
        - if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
        - run-parts /etc/logrotate.d/httpd-prerotate; \
        - fi \
        - endscript
        - postrotate
        - invoke-rc.d nginx rotate >/dev/null 2>&1
        - endscript
